#!/usr/bin/env python3

import argparse
import logging
import os
import requests
import git
import sys

from getpass import getpass
from markdown_to_confluence.confluence import Confluence
from markdown_to_confluence.convert import convtoconf, parse
"""Deploys Markdown posts to Confluenceo

This script is meant to be executed as either part of a CI/CD job or on an
adhoc basis.
"""

logging.basicConfig(format='%(asctime)s %(message)s', level=logging.INFO)
log = logging.getLogger(__name__)

SUPPORTED_FORMATS = ['.md', '.html', '.htm']


def get_environ_headers(prefix):
    """Returns a list of headers read from environment variables whose key
    starts with prefix.

    The header names are derived from the environment variable keys by
    stripping the prefix. The header values are set to the environment
    variable values.

    Arguments:
        prefix {str} -- The prefix of the environment variable keys which specify headers.
    """
    headers = []
    for key, value in os.environ.items():
        if key.startswith(prefix):
            header_name = key[len(prefix):]
            headers.append("{}:{}".format(header_name, value))
    return headers


def get_last_modified(repo):
    """Returns the paths to the last modified files in the provided Git repo

    Arguments:
        repo {git.Repo} -- The repository object
    """
    changed_files = repo.git.diff('HEAD~1..HEAD', name_only=True).split()
    for filepath in changed_files:
        if not filepath.startswith('content/'):
            changed_files.remove(filepath)
    return changed_files


def get_slug(filepath, prefix=''):
    """Returns the slug for a given filepath

    Arguments:
        filepath {str} -- The filepath for the post
        prefix {str} -- Any prefixes to the slug
    """
    slug, _ = os.path.splitext(os.path.basename(filepath))
    # Confluence doesn't support searching for labels with a "-",
    # so we need to adjust it.
    slug = slug.replace('-', '_')
    if prefix:
        slug = '{}_{}'.format(prefix, slug)
    return slug


def parse_args():
    parser = argparse.ArgumentParser(
        description='Converts and deploys a markdown post to Confluence')
    parser.add_argument(
        '--api_url',
        dest='api_url',
        default='http://localhost:8090/rest/api/',
        help=
        'The URL to the Confluence API (e.g. https://wiki.example.com/rest/api/)'
    )
    parser.add_argument(
        '--username',
        dest='username',
        default=os.getenv('CONFLUENCE_USERNAME'),
        help=
        'The username for authentication to Confluence (default: env(\'CONFLUENCE_USERNAME\'))'
    )
    parser.add_argument(
        '--password',
        dest='password',
        default=None,
        help=
        'The password for authentication to Confluence (default: env(\'CONFLUENCE_PASSWORD\'))'
    )
    parser.add_argument(
        '--space',
        dest='space',
        default=os.getenv('CONFLUENCE_SPACE'),
        help=
        'The Confluence space where the post should reside (default: env(\'CONFLUENCE_SPACE\'))'
    )
    parser.add_argument(
        '--ancestor_id',
        dest='ancestor_id',
        default=os.getenv('CONFLUENCE_ANCESTOR_ID'),
        help=
        'The Confluence ID of the parent page to place posts under (default: env(\'CONFLUENCE_ANCESTOR_ID\'))'
    )
    parser.add_argument(
        '--global_label',
        dest='global_label',
        default=os.getenv('CONFLUENCE_GLOBAL_LABEL'),
        help=
        'The label to apply to every post for easier discovery in Confluence (default: env(\'CONFLUENCE_GLOBAL_LABEL\'))'
    )
    parser.add_argument(
        '--header',
        metavar='HEADER',
        dest='headers',
        action='append',
        default=get_environ_headers('CONFLUENCE_HEADER_'),
        help=
        'Extra header to include in the request when sending HTTP to a server. May be specified multiple times. (default: env(\'CONFLUENCE_HEADER_<NAME>\'))'
    )
    parser.add_argument(
        '--dry-run',
        dest='dry_run',
        action='store_true',
        help=
        'Print requests that would be sent- don\'t actually make requests against Confluence (note: we return empty responses, so this might impact accuracy)'
    )
    parser.add_argument(
        '--force',
        action='store_true',
        help='Upload pages without checking for changes'
    )
    parser.add_argument(
        'posts',
        type=str,
        nargs='+',
        help=
        'Individual files to deploy to Confluence'
    )

    args = parser.parse_args()

    if not args.api_url:
        log.error('Please provide a valid API URL')
        sys.exit(1)

    return parser.parse_args()

class Page():
    def __init__(self, post_path, args, confluence):
        self.post_path = post_path
        self.ignore = True

        _, ext = os.path.splitext(post_path)
        if ext not in SUPPORTED_FORMATS:
            log.info('Skipping {} since it\'s not a supported format.'.format(
                post_path))
            return

        try:
            self.front_matter, markdown = parse(post_path)
        except Exception as e:
            log.error(
                'Unable to process {}. Normally not a problem, but here\'s the error we received: {}'
                .format(post_path, e))
            return

        if 'ignore' in self.front_matter:
            log.info(
                f'Page {post_path} has "ignore" set in front matter.  Ignoring.')
            return

        ext = post_path.split('.')[-1]

        if ext == 'md':
            # Normalize the content into whatever format Confluence expects
            self.html, self.attachments = convtoconf(markdown, front_matter=self.front_matter)
        else:
            self.html = markdown
            self.attachments = [] # TODO: support html attachments

        self.post_slug = get_slug(post_path)

        self.space = self.front_matter.get('space', args.space)

        self.tags = self.front_matter.get('tags', [])
        if args.global_label:
            self.tags.append(args.global_label)
        self.ignore = False
        self.children = []

    def deploy(self, args, confluence, parent_id):
        if 'parent' in self.front_matter and not parent_id:
            parent_title = self.front_matter['parent']
            parent = confluence.exists(title=parent_title, space=self.space)
            if not parent:
                log.error(f'Cannot find parent page "{parent_title}". Skipping {self.post_path}.')
                self.id = None
                return
            parent_id = parent['id']
        page = confluence.exists(title=self.front_matter['title'],
                                ancestor_id=parent_id,
                                space=self.space)
        if page:
            self.id = page['id']
            # FIXME: confluence sometimes changes the file so unchanged file will not match
            if not args.force and confluence.get_page_content(page['id']) == self.html.strip():
                log.info(f'Skipping {self.post_path} since there are no changes')
            else:
                confluence.update(page['id'],
                                content=self.html,
                                title=self.front_matter['title'],
                                tags=self.tags,
                                slug=self.post_slug,
                                space=self.space,
                                ancestor_id=parent_id,
                                page=page,
                                attachments=self.attachments)
        else:
            self.id = confluence.create(content=self.html,
                            title=self.front_matter['title'],
                            tags=self.tags,
                            slug=self.post_slug,
                            space=self.space,
                            ancestor_id=parent_id,
                            attachments=self.attachments)


def main():
    args = parse_args()

    if args.password is None:
        args.password = getpass()

    confluence = Confluence(api_url=args.api_url,
                            username=args.username,
                            password=args.password,
                            headers=args.headers,
                            dry_run=args.dry_run)

    if args.posts:
        changed_posts = [os.path.abspath(post) for post in args.posts]
        for post_path in changed_posts:
            if not os.path.exists(post_path) or not os.path.isfile(post_path):
                log.error('File doesn\'t exist: {}'.format(post_path))
                sys.exit(1)
    if not changed_posts:
        log.info('No post created/modified in the latest commit')
        return

    pages = [ p for p in (Page(post, args, confluence) for post in changed_posts) if not p.ignore ]
    page_map = dict((p.front_matter['title'], p) for p in pages)
    root_pages = []
    for p in pages:
        parent = p.front_matter.get('parent', None)
        if parent and parent in page_map:
            page_map[parent].children.append(p)
        else:
            root_pages.append(p)

    def deploy_pages(pages, offset = 0, parent_id = None):
        for p in pages:
            log.info('-' * offset + '> Attempting to deploy ' + p.front_matter['title'])
            p.deploy(args, confluence, parent_id)
            deploy_pages(p.children, offset + 4, p.id)

    deploy_pages(root_pages)

if __name__ == '__main__':
    main()
